# Generated by Django 4.2.1 on 2024-02-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training_organization',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
